artifacts_root : artifacts

document_ingestion:
  root_dir: artifacts/document_ingestion
  upload_dir: artifacts/document_ingestion/uploaded_files
  supported_extensions: [".pdf", ".docx", ".txt"]

document_validation:
  root_dir: artifacts/document_validation
  valid_dir: artifacts/document_validation/valid_files
  invalid_dir: artifacts/document_validation/invalid_files
  supported_extensions: [".pdf", ".docx", ".txt"]
  max_file_size_mb: 25
  min_words: 250

text_extraction:
  root_dir: artifacts/text_extraction
  valid_dir: artifacts/document_validation/valid_files
  extracted_dir: artifacts/text_extraction/extracted_texts

document_preprocessing:
  root_dir: artifacts/document_preprocessing
  extracted_dir: artifacts/text_extraction/extracted_texts
  preprocessed_dir: artifacts/document_preprocessing/preprocessed_files

chunking:
  root_dir: artifacts/chunking
  preprocessed_dir: artifacts/document_preprocessing/preprocessed_files
  chunked_dir: artifacts/chunking/chunked_files

summarizing:
  root_dir: artifacts/summarizing
  chunked_dir: artifacts/chunking/chunked_files
  summarized_chunks: artifacts/summarizing/summarized_chunks
  summarized_files: artifacts/summarizing/summarized_files